### ISSUE TITLE
Model reference

### ISSUE THREAD

**Issue by fengyonglv** [aerdem4/kaggle-quora-dup#4]
May I asked model in your solution,refer to any other reference ,such as paper?Thanks

**Comment by aerdem4** [comment]
As far as I remember, my solution was evolved from this public kernel:
https://www.kaggle.com/lystdo/lstm-with-word2vec-embeddings

Unfortunately, I didn't read related papers while working on this competition.

**Comment by fengyonglv** [comment]
Thanks your answer.I have learn much from your code.
And another question. In your postprocess.py ,this "TEST_TARGET_MEAN = 0.16",how to get 0.16 value?
Thanks.

**Comment by aerdem4** [comment]
I am happy to hear that it was useful for you, you are welcome.
TARGET_MEAN was used to get better score on the test set considering the class balance sensitivity of logloss. So outside of Kaggle, this is meaningless.
