### ISSUE TITLE
get_kcore_dict()'s return value might be wrong

### ISSUE THREAD

**Issue by elm200** [aerdem4/kaggle-quora-dup#6]
I have a doubt on this line.
https://github.com/aerdem4/kaggle-quora-dup/blob/master/non_nlp_feature_extraction.py#L41

Perhaps, this line should be something like:
```python
    return dict(zip(df_output["qid"], df_output["kcore"]))
```
so that the returned dict has qids as keys properly.

(Your code is very helpful. Thank you very much!)

**Comment by aerdem4** [comment]
Thanks for your suggestion. I have checked: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_dict.html It seems default orient is ‘dict’ (default) : dict like {column -> {index -> value}}. So it is a dictionary of a dictionary. For each column, it has a index to value dict, so qid to kcore.

**Comment by elm200** [comment]
Thank you for you comment.

https://github.com/aerdem4/kaggle-quora-dup/blob/master/non_nlp_feature_extraction.py#L34
```python
df_output = pd.DataFrame(data=g.nodes(), columns=["qid"])
```
Here, `df_output`'s index would be a sequence of integers which starts from `0` to `len(g.nodes()) - 1`.
This does not equal to `g.nodes()` itself, which would consist of the `qid` column.

I am sorry if I misunderstand something.

**Comment by aerdem4** [comment]
Thanks for pointing out. I tried to remember why I had implemented it that way. I guess it was a copy paste code from Kaggle forum: https://www.kaggle.com/c/quora-question-pairs/discussion/33371 
I think this is just a bad implementation but doesn't give wrong results. The created qid column is never used. kcore feature is set by using only index and qid's are integers: https://github.com/aerdem4/kaggle-quora-dup/blob/master/non_nlp_feature_extraction.py#L39
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.ix.html

**Comment by elm200** [comment]
Thanks for your comment again.

Unfortunaly, the line 39 has nothing to do with my point in this context.
https://github.com/aerdem4/kaggle-quora-dup/blob/master/non_nlp_feature_extraction.py#L39

```python
        df_output.ix[df_output.qid.isin(ck), "kcore"] = k
```
`df_output.qid.isin(ck)` gives a pandas Series with boolean values. In this case, `df_output.ix[df_output.qid.isin(ck), "kcore"] = k` is equivalent to `df_output.loc[df_output.qid.isin(ck), "kcore"] = k`. L39 is absolutely correct(I admit that `ix` method is a bit confusing and that is why it is now deprecated). However, L39 does not change either `df_output.index` or `df_output["qid"]`  at all.

The problem is the line 41 as I mentioned in my first comment.
https://github.com/aerdem4/kaggle-quora-dup/blob/master/non_nlp_feature_extraction.py#L41
```python
 return df_output.to_dict()["kcore"]
```
`df_output.to_dict()["kcore"]` gives a dict (index -> kcore), while my suggestion `dict(zip(df_output["qid"], df_output["kcore"]))` gives a dict (qid -> kcore). And the index and the qid column are different in `df_output` (In my environment (networkx version 2.2), the index was like `[0, 1, 2, 3...]`, while the qid column was like `[0, 2, 4, 6..]`. The index and the qid column could be the same coincidentally sometimes, but they are different values in general, I guess). 

Therefore, `df_output.to_dict()["kcore"]` and `dict(zip(df_output["qid"], df_output["kcore"]))` give different results. 

If you want a dict with the qid as the keys, then  `dict(zip(df_output["qid"], df_output["kcore"]))` should be what you want.

If you run the code with a small amount of data, you will see the results above (I actually did it).
Probably, the original kernel was wrong in the first place...

**Comment by aerdem4** [comment]
What I want to say is that g.nodes() returns node ids sorted. Therefore, df_output.index must be equal to df_output["qid"] since qids are from 0 to n adjacent. Since they are the same in this case, the code must have worked correct, but implementing it your way is safer and more readable. My implementation wouldn't work with any other qids which are not adjacent [0, n]

**Comment by elm200** [comment]
I appreciate your information. Finally, I understand your point.

I think that you use `networkx` with the version older than 2.2. Probably, now the implementation has changed and `g.nodes()` would not give sorted values any longer(this is only my guess and I have not verified it yet). This `networkx` version problem has also something to do with another issue https://github.com/aerdem4/kaggle-quora-dup/issues/1 .

Anyway, thank you very much for the discussion here. Now I can feel more confident in understanding your code.
