### ISSUE TITLE
Possible to include some trained weights?

### ISSUE THREAD

**Issue by jembishop** [aerdem4/kaggle-quora-dup#8]
Hi I was interested in playing about with this model, but I was wondering instead of hiring an AWS server to run the model, is it possible to include some trained weights so we can use the model without training it? 

Thanks

**Comment by aerdem4** [comment]
Thanks for your interest. Pre-trained embeddings would be basically for each Quora question, therefore I don't see a general use case for it. How do you plan to use them? In which problem? On the other hand, current model doesn't need any expensive hardware. It can run on a laptop with Nvidia 950m and 8 GB RAM.

**Comment by aerdem4** [comment]
Ah my bad, you didn't mean the sentence embeddings but the model weights. It is indeed possible. Nowadays, my GPU is busy with some Kaggle competitions. I can train a model and add its weights to the repo when I find spare computing time. But if you want to use it for a real life problem, it should be trained without non-nlp features.

**Comment by jembishop** [comment]
The application was for a text adventure game where the user could input a question and it could be matched (using a model such as this) to a list of predefined questions. Don't know how well that will work in practice as but this  seems like a good starting point, as it is lightweight and therefore should (?) be able to process ~100 question pairs in ~1s. 

Yes I should have read the requirements my bad, I can actually handle this on my laptop. I still think it would be valuable to have the weights on the repo though. Thanks for helping me out.

**Comment by aerdem4** [comment]
For your use case, non-NLP features (graph features) should be discarded. They were only helping for utilizing Kaggle's sampling bias: https://github.com/aerdem4/kaggle-quora-dup/blob/master/model.py#L149

Btw, I have noticed that my code needs serious refactoring. It was 2 years ago and I forgot to convert it to a reusable ML pipeline just after the competition. Hopefully, when I find time, I can convert it to something that can be used in real life problems directly.

**Comment by jembishop** [comment]
Cool, that would be awesome if you get round to that.
